# Generated by Django 4.0.5 on 2022-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregadosapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
                ('matricula', models.IntegerField(max_length=10)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Empregado',
        ),
    ]
