# Generated by Django 4.0.5 on 2022-06-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empregadosapi', '0004_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
    ]
