# Generated by Django 4.0.5 on 2022-06-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregadosapi', '0006_aluno_foto_aluno_nome_turma_ano_turma_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default=None, max_length=50, upload_to=''),
        ),
    ]
