# Generated by Django 4.0.5 on 2022-06-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregadosapi', '0007_alter_aluno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
